### ISSUE TITLE
Thanks & some queries on the nice docker

### ISSUE THREAD

**Issue by skwskwskwskw** [nielsborie/ml-docker#5]
Hi Niels, 

I was actually trying to install kaggle docker (python) docker but to no avail due to some issue - raised on the kaggle docker but yet to get any response. Many thanks as I came across this useful docker.

I just trying around with the docker only past 3 days (pretty new to it I must say). My queries: 

1. The docker image installed successfully if I used 'pull' command. However if I download from github and cd to the directory & run 'build -t' command, there's actually a bunch of error (didn't manage to snapshot it) as well as leaving intermediary image. Do you know how to resolve this issue?

2. Reason why I would like to pull it directly because I want to install new packages. 
Say if I want to install more packages on the currently installed image, is there an easy way out without duplicating the image or rebuilding from scratch? (My main goal is to edit the image).

3. By the way, why you used the jupyter/tensorflow-notebook build: 5811dcb711ba?

Thanks.

**Comment by nielsborie** [comment]
Hi, 

Sorry to answer so late... I'm going to review and maybe refactor this repository so I'll take this opportunity to answer you (it could help some people).

1. It's been a while since I've started local construction again, I'll try on my own and I'll get back to you...

2. You have two options, depending on what you want to do with it afterwards. If you want to install packages in a permanent and reusable way, you have to add the libraries in the DockerFile and either rebuild the image locally or push it to a public/ private docker registry (example: DockerHub ). 
**Or** you can manually install your libraries directly into your container (with the `docker exec -it ML-env /bin/bash` command and then run the `pip install`,` apt-get install` inside the container... ). As long as your container is "alive" (i-e as long as you don't run `docker rm my_container`) you will have your additional libraries ready to use! 

3. For `jupyter/tensorflow-notebook` I had chosen an arbitrary version of this image because I wanted my version to be stable. I'm thinking of doing a global upgrade of all the libraries.

I hope I've answered all your questions, even 4 months later! 

Cheers
